### ISSUE TITLE
API design

### ISSUE THREAD

**Issue by cncolder** [brandon93s/micro-superstruct#1]
IMO the more [micro](https://github.com/zeit/micro)-style is like this:

```js
const { struct } = require('superstruct')
const { send } = require('micro')
const validate = require('micro-superstruct')

// define a Superstruct `struct`
const Unicorn = struct({
  name: 'string',
  age: 'number',
  color: 'string'
})

// create a validator
const validator = validate(Unicorn)

// write your Micro API
module.exports = async (req, res) => {
  const body = await validator(req)
  send(res, 200, body)
}
```

**Comment by brandon93s** [comment]
Hello @cncolder,

Thanks for the feedback. The [community](https://github.com/amio/awesome-micro) has largely adopted a pattern of composition that allows for companion modules and API handler logic to remain isolated from one another. This pattern allows for `micro-superstruct` to be added to or removed from your project without altering your handlers. 

Others:

- https://github.com/possibilities/micro-cors
- https://github.com/joakimbeng/micro-compress
- https://github.com/onbjerg/micro-boom
- https://github.com/dotcypress/micro-stats
- [More...](https://github.com/amio/awesome-micro)
